// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDLs00ypinogjNfW0mT_7-7uaXsSXDd8Y',
    appId: '1:454248900345:android:77aab696bdbd2279d7e428',
    messagingSenderId: '454248900345',
    projectId: 'daad-64fee',
    storageBucket: 'daad-64fee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcvnoEnFW0AMmF8vuDQoAqHOOWfqMLYD4',
    appId: '1:454248900345:ios:32fb9b24753c2301d7e428',
    messagingSenderId: '454248900345',
    projectId: 'daad-64fee',
    storageBucket: 'daad-64fee.firebasestorage.app',
    iosBundleId: 'com.zbooma.daad',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA54DU3Tpzge2XJidHp6ncUT8qDJTLxSlE',
    appId: '1:454248900345:web:fe51da131a903433d7e428',
    messagingSenderId: '454248900345',
    projectId: 'daad-64fee',
    authDomain: 'daad-64fee.firebaseapp.com',
    storageBucket: 'daad-64fee.firebasestorage.app',
    measurementId: 'G-69YJ38SVJ9',
  );

}